import {
  Book,
  Briefcase,
  Camera,
  Clapperboard,
  Code,
  Coffee,
  Dumbbell,
  FlaskConical,
  Folder,
  Gamepad2,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Music,
  Newspaper,
  Palette,
  Plane,
  Search,
  ShoppingCart,
  Star,
  Utensils,
  Wallet,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const WORKSPACE_ICONS: Record<string, LucideIcon> = {
  folder: Folder,
  briefcase: Briefcase,
  home: Home,
  code: Code,
  "shopping-cart": ShoppingCart,
  search: Search,
  book: Book,
  music: Music,
  camera: Camera,
  heart: Heart,
  star: Star,
  globe: Globe,
  zap: Zap,
  coffee: Coffee,
  "gamepad-2": Gamepad2,
  "graduation-cap": GraduationCap,
  plane: Plane,
  palette: Palette,
  "flask-conical": FlaskConical,
  newspaper: Newspaper,
  wallet: Wallet,
  dumbbell: Dumbbell,
  utensils: Utensils,
  clapperboard: Clapperboard,
};
