import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { reactRouter } from "@react-router/dev/vite";
import tailwindcss from "@tailwindcss/vite";
import alchemyPlugin from "alchemy/cloudflare/react-router";
import { defineConfig, type PluginOption } from "vite";
import devtoolsJson from "vite-plugin-devtools-json";
import tsconfigPaths from "vite-tsconfig-paths";

// `alchemyPlugin()` reads .alchemy/local/wrangler.jsonc, generated by
// `alchemy dev` / `alchemy deploy`. A fresh clone running `pnpm build`
// (CI before any deploy) would crash without it. Gate the plugin so
// CI-only build still works; Alchemy itself owns deploys via `pnpm deploy`.
//
// Two-step gate: file must exist AND alchemyPlugin() must return a non-null
// value. The plugin returns null during react-router typegen runs.
const wranglerPath = resolve(__dirname, ".alchemy/local/wrangler.jsonc");
const maybePlugin = existsSync(wranglerPath) ? alchemyPlugin() : null;
const alchemyPlugins: PluginOption[] = maybePlugin ? [maybePlugin as PluginOption] : [];

export default defineConfig({
  plugins: [...alchemyPlugins, tailwindcss(), reactRouter(), tsconfigPaths(), devtoolsJson()],
  server: {
    open: true,
    // DEV_APP_URL_LIST locks dev local APP_URL host to localhost:5173 (the
    // GitHub OAuth callback URL is registered there). If 5173 is occupied
    // (e.g. multi-workspace runs), strictPort makes vite fail loudly instead
    // of silently moving to 5174 — a moved port would mismatch the OAuth
    // callback and BetterAuth trustedOrigins, surfacing as INVALID_ORIGIN
    // far from the root cause.
    port: 5173,
    strictPort: true,
    // Vite 6+ tightened the dev-server CORS default to localhost/127.0.0.1
    // only (CVE-2025-30208), which blocks `chrome-extension://…` preflights
    // before they ever reach `workers/app.ts`'s CORS wrapper. Re-allow
    // chrome-extension here so the extension wizard can talk to the local
    // worker; the actual trust list for cross-origin API calls still lives
    // in app/lib/cors.ts (shared with BetterAuth's trustedOrigins).
    cors: {
      origin: [
        /^https?:\/\/(?:(?:[^:]+\.)?localhost|127\.0\.0\.1|\[::1\])(?::\d+)?$/,
        /^chrome-extension:\/\/.+$/,
      ],
    },
  },
  build: {
    minify: true,
  },
  // When the Alchemy plugin is absent (fresh clone, `pnpm build` in CI),
  // `cloudflare:*` specifiers have no native resolver. Register them as
  // SSR builtins so Vite externalizes them; the CF Workers runtime resolves
  // them at deploy time. The Alchemy plugin does the same internally when
  // present.
  ...(alchemyPlugins.length === 0 && {
    environments: {
      ssr: {
        resolve: {
          builtins: [
            "cloudflare:workers",
            "cloudflare:email",
            "cloudflare:node",
            "cloudflare:sockets",
            "cloudflare:workflows",
          ],
        },
      },
    },
  }),
});
